FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json* ./
COPY apps/web/package.json ./apps/web/
COPY packages/shared/package.json ./packages/shared/

RUN npm install --workspaces --include-workspace-root

COPY packages/shared ./packages/shared
COPY apps/web ./apps/web

EXPOSE 5173
WORKDIR /app/apps/web
CMD ["npm", "run", "dev"]
